version: "3.8"
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: book_pass
      MYSQL_DATABASE: book_db
      MYSQL_USER: book_user
      MYSQL_PASSWORD: book_pass
    volumes:
      - book_db_data:/var/lib/mysql
    ports:
      - "4306:3306"
    networks:
      - my-network
  elasticsearch:
    platform: linux/amd64
    image: elasticsearch:8.7.1
    ports:
      - 9200:9200
    restart: always
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - my-network
  kibana:
    platform: linux/amd64
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    ports:
      - 5601:5601
    volumes:
      - kibana-data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    restart: always
    networks:
      - my-network
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network

networks:
  my-network:
    external:
      name: my-network

volumes:
  book_db_data:
  kibana-data:
  elasticsearch-data: